Repository TeamPophory/pophory-iOS, pull requests merged in 2023-08, with the labels that each got.

#190 [Chore] #189 사진 상세보기 공유하기 기능 수정
  pophory-iOS/Network/API/AlbumAPI.swift
  pophory-iOS/Network/Models/Photos.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/PhotoDetail/ViewController/PhotoDetailViewController.swift
Labels: 다예✨, Chore 🧹

#191 [Chore] #172 - network v2
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Global/Extensions/UIViewController+Extension.swift
  pophory-iOS/Global/Protocols/NextButtonDelegate.swift
  pophory-iOS/Network/API/AuthAPI.swift
  pophory-iOS/Network/API/MemberAPI.swift
  pophory-iOS/Network/Common/AppleLoginManager.swift
  pophory-iOS/Network/Common/AsyncMoyaProvider.swift
  pophory-iOS/Network/Models/Member/FetchSignUpRequestDTO.swift
  pophory-iOS/Network/Models/Member/PostIsDuplicatedDTO.swift
  pophory-iOS/Network/Repository/DefaultMemberRepository.swift
  pophory-iOS/Network/Repository/Protocol/AuthRepository.swift
  pophory-iOS/Network/Repository/Protocol/MemberRepository.swift
  pophory-iOS/Screen/Auth/Network/AuthNetworkManager.swift
  pophory-iOS/Screen/Auth/ViewControllers/IDInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/NameInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/PickAlbumCoverViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/StartPophoryViewController.swift
  pophory-iOS/Screen/Auth/Views/NameInputView.swift
  pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
  pophory-iOS/Screen/Onboarding/ViewContoller/OnboardingViewController.swift
Labels: Chore 🧹

#195 [Fix] #194 - 2차 스프린트 QA 반영
  pophory-iOS/Global/Utilities/DateManager.swift
  pophory-iOS/Screen/AddPhoto/View/AddPhotoView.swift
  pophory-iOS/Screen/AddPhoto/View/PhotoInfoStackView.swift
  pophory-iOS/Screen/AddPhoto/View/StudioCollectionViewCell.swift
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
  pophory-iOS/Screen/AddPhoto/ViewController/CalendarModalViewController.swift
  pophory-iOS/Screen/AddPhoto/ViewController/StudioModalViewController.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/TabBar/TabBarViewController.swift
Labels: 다예✨, Fix 🔧

#196 [Fix] #188 - 사진 용량 3MB 제한
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Base/BasePHPickerViewController.swift
  pophory-iOS/Global/Extensions/UIImage+Extension.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/TabBar/TabBarViewController.swift
Labels: 다예✨, Fix 🔧

#202 [Fix] #200 - 이미지 용량 제한 수정
  pophory-iOS/Global/Components/Base/BasePHPickerViewController.swift
  pophory-iOS/Global/Extensions/UIImage+Extension.swift
Labels: 다예✨, Fix 🔧

#193 [Fix] #192 - 사진 개수 초과 시 popUpView 뜨는 오류 수정
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
Labels: Fix 🔧, 윤서💡

#204 [Setting] #199 - Crashlytics 부착
  pophory-iOS.xcodeproj/project.pbxproj
Labels: Setting ⚙️, 윤서💡

#198 [Setting] #197 - Sentry SDK 부착
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Resources/AppDelegate.swift
Labels: Setting ⚙️, 다예✨

#205 [Fix] #201 - 2차 스프린트 qa 반영
  pophory-iOS/Global/Components/PophoryButtonBuilder.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/AlbumDetail/View/AlbumDetailView.swift
  pophory-iOS/Screen/AlbumDetail/View/PhotoCollectionViewCell.swift
  pophory-iOS/Screen/ChangeSort/ChangeSortViewController.swift
  pophory-iOS/Screen/EditAlbumCover/View/AlbumCoverCollectionViewCell.swift
  pophory-iOS/Screen/EditAlbumCover/View/EditAlbumView.swift
  pophory-iOS/Screen/HomeAlbum/HomeAlbumView.swift
  pophory-iOS/Screen/HomeAlbum/HomeAlbumViewController.swift
  pophory-iOS/Screen/Onboarding/View/OnboardingView.swift
  pophory-iOS/Screen/PhotoDetail/View/PhotoDetailView.swift
  pophory-iOS/Screen/TabBar/TabBarViewController.swift
Labels: Chore 🧹, Fix 🔧

#207 [Fix] #206 - 사진 추가 플로우 수정
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
Labels: 다예✨, Fix 🔧
