Repository TeamPophory/pophory-iOS, pull requests merged in 2023-07, with the labels that each got.

#19 [Setting] #18 - Main스토리보드 삭제, Bundle ID 수정
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Resources/Base.lproj/Main.storyboard
  pophory-iOS/Global/Supporting Files/Info.plist
Labels: Setting, 다예

#21 [Chore] #18 - 빌드오류 수정
  pophory-iOS.xcodeproj/project.pbxproj
Labels: 다예, Chore

#44 [Fix] #36 사진 추가 뷰 Conflict 해결
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/PophoryButton.swift
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Resources/Assets.xcassets/calanderIcon.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/calanderIcon.imageset/calanderIcon.svg
  pophory-iOS/Global/Resources/Assets.xcassets/downIcon.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/downIcon.imageset/downIcon.svg
  pophory-iOS/Global/Resources/Assets.xcassets/logIcon.imageset/logo.svg
  pophory-iOS/Global/Resources/Assets.xcassets/logIcon.imageset/타이포.svg
  pophory-iOS/Global/Resources/Assets.xcassets/searchIcon.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/searchIcon.imageset/searchIcon.svg
  pophory-iOS/Global/Resources/Assets.xcassets/tabBarEditAlbumIcon.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/tabBarEditAlbumIcon.imageset/addPhoto.svg
  pophory-iOS/Global/Resources/Assets.xcassets/tabBarEditAlbumIcon.imageset/사진추가버튼.svg
  pophory-iOS/Screen/AddPhoto/View/AddPhotoView.swift
  pophory-iOS/Screen/AddPhoto/View/PhotoAlbumCollectionViewCell.swift
  pophory-iOS/Screen/AddPhoto/View/PhotoInfoStackView.swift
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
  pophory-iOS/Screen/HomeAlbum/HomeAlbumView.swift
  pophory-iOS/Screen/TabBar/TabBarViewController.swift
Labels: 다예✨, fix

#47 [Add] #43 - PretendardBold 폰트 추가
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Consts/FontLiterals.swift
  pophory-iOS/Global/Resources/Fonts/Pretendard-Bold.otf
  pophory-iOS/Global/Supporting Files/Info.plist
Labels: 준☀️, Add

#42 [Feat] #20 - 온보딩 UI 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Global/Components/PophoryButton.swift
  pophory-iOS/Global/Components/PophoryButtonBuilder.swift
  pophory-iOS/Global/Components/PophoryNavigationConfigurator.swift
  pophory-iOS/Global/Extensions/UILabel+Extension.swift
  pophory-iOS/Global/Extensions/UIScreen+Extension.swift
  pophory-iOS/Global/Extensions/UIView+Extension.swift
  pophory-iOS/Global/Extensions/UIViewController+Extension.swift
  pophory-iOS/Global/Protocols/KeyboardFollowable.swift
  pophory-iOS/Screen/AddPhoto/View/AddPhotoView.swift
  pophory-iOS/Screen/Auth/PickAlbumButtonCollectionViewCell.swift
  pophory-iOS/Screen/Auth/PickAlbumCoverViewController.swift
  pophory-iOS/Screen/Auth/StartPophoryViewController.swift
  pophory-iOS/Screen/Auth/Views/IDInputView.swift
  pophory-iOS/Screen/Auth/Views/NameInputView.swift
  pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
  pophory-iOS/Screen/Auth/Views/StartPophoryView.swift
  pophory-iOS/Screen/Onboarding/OnboardingContentCollectionViewCell.swift
  pophory-iOS/Screen/Onboarding/OnboardingView.swift
  pophory-iOS/Screen/Onboarding/OnboardingViewController.swift
  pophory-iOS/Screen/TabBar/TabBarViewController.swift
Labels: 준☀️

#62 [Chore] #61 앨범 커버 관련 수정
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_collectBook.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_collectBook.imageset/ic_album_cover_collectBook.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_collectBook.imageset/ic_album_cover_collectBook@2x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_collectBook.imageset/ic_album_cover_collectBook@3x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_friends.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_friends.imageset/ic_album_cover_friends.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_friends.imageset/ic_album_cover_friends@2x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_friends.imageset/ic_album_cover_friends@3x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love.imageset/ic_album_cover_love.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love.imageset/ic_album_cover_love@2x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love.imageset/ic_album_cover_love@3x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_myAlbum.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_myAlbum.imageset/ic_album_cover_myAlbum.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_myAlbum.imageset/ic_album_cover_myAlbum@2x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_myAlbum.imageset/ic_album_cover_myAlbum@3x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCoverProfile/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCoverProfile/albumCoverProfile1.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCoverProfile/albumCoverProfile1.imageset/albumCoverProfile1.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCoverProfile/albumCoverProfile2.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCoverProfile/albumCoverProfile2.imageset/albumCoverProfile2.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCoverProfile/albumCoverProfile3.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCoverProfile/albumCoverProfile3.imageset/albumCoverProfile3.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCoverProfile/albumCoverProfile4.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCoverProfile/albumCoverProfile4.imageset/albumCoverProfile4.svg
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/onboardingImg1.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/onboardingImg1.imageset/onboardingImg1.svg
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/onboardingImg2.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/onboardingImg2.imageset/onboardingImg2.svg
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/onboardingImg3.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/onboardingImg3.imageset/onboardingImg3.svg
  pophory-iOS/Network/Models/Album/PatchAlbumListResponseDTO.swift
  pophory-iOS/Screen/HomeAlbum/HomeAlbumView.swift
  pophory-iOS/Screen/HomeAlbum/HomeAlbumViewController.swift
Labels: 다예✨, Chore

#56 [Feat] 사진추가 뷰 플로우 구현 & 커스텀 바텀시트
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Modal/CustomModalPresentationController.swift
  pophory-iOS/Global/Components/Modal/CustomModalTransitionDelegate.swift
  pophory-iOS/Global/Utilities/DateManager.swift
  pophory-iOS/Screen/AddPhoto/View/AddPhotoView.swift
  pophory-iOS/Screen/AddPhoto/View/StudioCollectionViewCell.swift
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
  pophory-iOS/Screen/AddPhoto/ViewController/CalendarModalViewController.swift
  pophory-iOS/Screen/AddPhoto/ViewController/StudioModalViewController.swift
Labels: 다예✨, Feat

#57 [Feat] #54 회원 정보등록 API 및 화면 연결 구현
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Network/Repository/DefaultMemberRepository.swift
  pophory-iOS/Screen/Auth/IDInputViewController.swift
  pophory-iOS/Screen/Auth/NameInputViewController.swift
  pophory-iOS/Screen/Auth/PickAlbumCoverViewController.swift
  pophory-iOS/Screen/Auth/Views/IDInputView.swift
  pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
Labels: 준☀️, Feat

#69 [Feat] #58 사진 추가 뷰 - 앨범, 사진관 API 연결
  pophory-iOS/Screen/AddPhoto/View/PhotoAlbumCollectionViewCell.swift
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
  pophory-iOS/Screen/AddPhoto/ViewController/StudioModalViewController.swift
Labels: 다예✨, Feat

#68 [Feat] 내 앨범 정렬 방식 변경 모달 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Resources/Assets.xcassets/defaultPhotoIcon.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/defaultPhotoIcon.imageset/defaultPhotoIcon.svg
  pophory-iOS/Global/Resources/SceneDelegate.swift
  pophory-iOS/Network/Common/BaseTargetType.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/AlbumDetail/ChangeSort/ChangeSortViewController.swift
  pophory-iOS/Screen/AlbumDetail/View/AlbumDetailView.swift
  pophory-iOS/Screen/ChangeSort/ChangeSortView.swift
  pophory-iOS/Screen/ChangeSort/ChangeSortViewController.swift
Labels: 준혁💫, Add

#74 [Chore] #73 - bundle identifier 수정
  pophory-iOS.xcodeproj/project.pbxproj
Labels: 준☀️, Chore

#67 [Feat] #59 - 사진 디테일 뷰 UI 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/PophoryNavigationController.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/PhotoDetail/View/PhotoDetailView.swift
  pophory-iOS/Screen/PhotoDetail/ViewController/PhotoDetailViewController.swift
Labels: Feat, 윤서💡

#75 [Feat] 내 앨범, 일러스트 추가 기능 구현
  pophory-iOS/Network/Models/Photos.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/AlbumDetail/View/AlbumDetailView.swift
  pophory-iOS/Screen/AlbumDetail/View/PhotoCollectionViewCell.swift
Labels: 준혁💫, Add

#70 [Feat] 사진 정렬 방식 기능 대응
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/AlbumDetail/View/AlbumDetailView.swift
Labels: 준혁💫, Add

#76 [Chore] #60 NavbarConfigurator 수정
  pophory-iOS/Global/Components/PophoryNavigationConfigurator.swift
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Resources/Assets.xcassets/alarm-1.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/alarm-1.imageset/alarm-1.svg
  pophory-iOS/Global/Resources/Assets.xcassets/alarm.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/alarm.imageset/alarm.svg
  pophory-iOS/Global/Resources/Assets.xcassets/delete-1.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/delete-1.imageset/delete-1.svg
  pophory-iOS/Global/Resources/Assets.xcassets/delete.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/delete.imageset/delete.svg
  pophory-iOS/Global/Resources/Assets.xcassets/my.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/my.imageset/my.svg
  pophory-iOS/Global/Resources/Assets.xcassets/right.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/right.imageset/right.svg
  pophory-iOS/Global/Resources/Assets.xcassets/setting.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/setting.imageset/setting.svg
  pophory-iOS/Global/Resources/Assets.xcassets/up.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/up.imageset/up.svg
  pophory-iOS/Global/Resources/Assets.xcassets/x.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/x.imageset/x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/내서랍.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/내서랍.imageset/내서랍.svg
Labels: 준☀️, Feat

#77 [Feat] #72 - 커스텀 팝업뷰 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/PophoryButton.swift
  pophory-iOS/Global/Components/PophoryButtonBuilder.swift
  pophory-iOS/Global/Components/PophoryPopupView.swift
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Resources/Assets.xcassets/img_albumfull.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/img_albumfull.imageset/img_albumfull.svg
  pophory-iOS/Global/Resources/Assets.xcassets/img_congratuation.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/img_congratuation.imageset/img_congratuation.svg
Labels: 준☀️, Feat

#78 [Feat] #63 사진 추가 API 연결
  pophory-iOS/Global/Utilities/DateManager.swift
  pophory-iOS/Network/API/PhotoAPI.swift
  pophory-iOS/Network/Models/Photo/PostPhotoRequestDTO.swift
  pophory-iOS/Network/Repository/DefaultPhotoRepository.swift
  pophory-iOS/Network/Repository/Protocol/PhotoRepository.swift
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
  pophory-iOS/Screen/AddPhoto/ViewController/CalendarModalViewController.swift
  pophory-iOS/Screen/AddPhoto/ViewController/StudioModalViewController.swift
Labels: 다예✨, Feat

#100 [Add] #90 갤러리 권한에 따른 분기처리
  pophory-iOS/Global/Components/Base/BaseImagePickerViewController.swift
  pophory-iOS/Screen/TabBar/TabBarViewController.swift
Labels: 다예✨, Add

#102 [Chore] #101 릴리즈를 위한 준비중 기능 삭제
  pophory-iOS/Screen/AddPhoto/View/AddPhotoView.swift
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
Labels: 다예✨, Chore

#105 [Chore] #104 사진 추가 뷰 네트워크 수정
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
Labels: 다예✨, Chore 🧹

#109 [Chore] #96 사진 추가 뷰 UI 수정
  pophory-iOS/Global/Consts/FontLiterals.swift
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Resources/Assets.xcassets/ckeckBigIconWhite.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/ckeckBigIconWhite.imageset/ckeckBigIconWhite.svg
  pophory-iOS/Screen/AddPhoto/View/AddPhotoView.swift
  pophory-iOS/Screen/AddPhoto/View/PhotoAlbumCollectionViewCell.swift
  pophory-iOS/Screen/AddPhoto/View/PhotoInfoStackView.swift
  pophory-iOS/Screen/AddPhoto/View/StudioCollectionViewCell.swift
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
  pophory-iOS/Screen/AddPhoto/ViewController/StudioModalViewController.swift
Labels: 다예✨, Chore 🧹

#112 [Chore] #110 PHPickerViewController 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Base/BaseImagePickerViewController.swift
  pophory-iOS/Global/Components/Base/BasePHPickerViewController.swift
  pophory-iOS/Global/Components/LimitedImagePicker/PHPickerLimitedPhotoCollectionViewCell.swift
  pophory-iOS/Global/Components/LimitedImagePicker/PHPickerLimitedPhotoViewController.swift
  pophory-iOS/Global/Supporting Files/Info.plist
  pophory-iOS/Screen/AddPhoto/ViewController/CalendarModalViewController.swift
  pophory-iOS/Screen/TabBar/TabBarViewController.swift
Labels: 다예✨, Chore 🧹

#114 [Feat] 마이페이지, 설정 API 연결
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  pophory-iOS/Global/Components/Base/BaseViewController.swift
  pophory-iOS/Global/Components/PophoryPopupView.swift
  pophory-iOS/Global/Components/PophoryWebViewController.swift
  pophory-iOS/Global/Extensions/UserDefault+Extension.swift
  pophory-iOS/Network/Common/BaseURLConstant.swift
  pophory-iOS/Screen/AlbumDetail/View/PhotoCollectionViewCell.swift
  pophory-iOS/Screen/Auth/IDInputViewController.swift
  pophory-iOS/Screen/Mypage/Network/MyPageNetworkManager.swift
  pophory-iOS/Screen/Mypage/View/MyPageRootView.swift
  pophory-iOS/Screen/Mypage/ViewController/MypageViewController.swift
  pophory-iOS/Screen/Settings/View/SettingsRootView.swift
  pophory-iOS/Screen/Settings/ViewController/SettingsViewController.swift
Labels: 다은🔥, Feat 🛠️

#118 [Fix] #117 - Pophory Navibar, Configurator 수정
  pophory-iOS/Global/Components/PophoryNavigationConfigurator.swift
  pophory-iOS/Global/Components/PophoryNavigationController.swift
  pophory-iOS/Global/Extensions/UIViewController+Extension.swift
  pophory-iOS/Global/Resources/SceneDelegate.swift
  pophory-iOS/Screen/Auth/IDInputViewController.swift
  pophory-iOS/Screen/Auth/NameInputViewController.swift
Labels: 준☀️, Fix 🔧

#120 [Feat] #119 앨범 빈 배열 & 앨범 ID 값 수정
  pophory-iOS/Network/Common/BaseURLConstant.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/HomeAlbum/HomeAlbumViewController.swift
Labels: 다예✨, Fix 🔧

#116 Fix/#106 login flow
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Extensions/String+Extension.swift
  pophory-iOS/Global/Extensions/UILabel+Extension.swift
  pophory-iOS/Global/Extensions/UIViewController+Extension.swift
  pophory-iOS/Global/Resources/Assets.xcassets/checkBigIconWhite.imageset/Check_Big.svg
  pophory-iOS/Global/Resources/Assets.xcassets/checkBigIconWhite.imageset/Contents.json
  pophory-iOS/Screen/Auth/IDInputViewController.swift
  pophory-iOS/Screen/Auth/NameInputViewController.swift
  pophory-iOS/Screen/Auth/PickAlbumButtonCollectionViewCell.swift
  pophory-iOS/Screen/Auth/Views/IDInputView.swift
  pophory-iOS/Screen/Auth/Views/NameInputView.swift
  pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
  pophory-iOS/Screen/Auth/Views/StartPophoryView.swift
Labels: 준☀️, Chore 🧹

#123 [Chore] #112 - 온보딩에서 진입시 네비바 실종 이슈
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/Onboarding/OnboardingView.swift
  pophory-iOS/Screen/Onboarding/OnboardingViewController.swift
Labels: 준☀️, Chore 🧹, Fix 🔧

#128 [Feat] #64 - 소셜 로그인, 자동로그인 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Global/Components/PophoryButton.swift
  pophory-iOS/Global/Components/PophoryButtonBuilder.swift
  pophory-iOS/Global/Extensions/UIViewController+Extension.swift
  pophory-iOS/Global/Resources/AppDelegate.swift
  pophory-iOS/Global/Resources/SceneDelegate.swift
  pophory-iOS/Network/API/AlbumAPI.swift
  pophory-iOS/Network/API/AuthAPI.swift
  pophory-iOS/Network/API/MemberAPI.swift
  pophory-iOS/Network/API/StudiosAPI.swift
  pophory-iOS/Network/Common/BaseTargetType.swift
  pophory-iOS/Network/Common/PophoryTokenManager.swift
  pophory-iOS/Network/Models/Auth/LoginAPIDTO.swift
  pophory-iOS/Network/Models/Auth/PostIdentityTokenDTO.swift
  pophory-iOS/Network/Models/Member/PostIsDuplicatedDTO.swift
  pophory-iOS/Network/Repository/DefaultAuthRepository.swift
  pophory-iOS/Network/Repository/DefaultMemberRepository.swift
  pophory-iOS/Network/Repository/Protocol/AuthRepository.swift
  pophory-iOS/Network/Repository/Protocol/MemberRepository.swift
  pophory-iOS/Screen/Auth/ViewControllers/IDInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/NameInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/PickAlbumCoverViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/StartPophoryViewController.swift
  pophory-iOS/Screen/Auth/Views/Cells/PickAlbumButtonCollectionViewCell.swift
  pophory-iOS/Screen/Auth/Views/Cells/SignUpIndicatorCollectionViewCell.swift
  pophory-iOS/Screen/Auth/Views/IDInputView.swift
  pophory-iOS/Screen/Auth/Views/NameInputView.swift
  pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
  pophory-iOS/Screen/Onboarding/OnboardingViewController.swift
  pophory-iOS/Screen/Onboarding/View/Cell/OnboardingContentCollectionViewCell.swift
  pophory-iOS/Screen/Onboarding/View/OnboardingView.swift
  pophory-iOS/Screen/Onboarding/ViewContoller/OnboardingViewController.swift
Labels: Feat 🛠️, Chore 🧹

#125 [Fix] 팝업 리팩토링, 버튼 버그 수정
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/PophoryButton.swift
  pophory-iOS/Global/Components/PophoryButtonBuilder.swift
  pophory-iOS/Global/Components/PophoryPopupView.swift
  pophory-iOS/Global/Components/PophoryPopupViewController.swift
  pophory-iOS/Global/Consts/PopupType.swift
  pophory-iOS/Global/Extensions/NSMutableAttributedString+Extension.swift
  pophory-iOS/Global/Extensions/UIButton+Extension.swift
  pophory-iOS/Global/Extensions/UIViewController+Extension.swift
  pophory-iOS/Screen/.keep
Labels: 다은🔥, Fix 🔧

#131 [Fix] 자잘한 버그들 수정
  pophory-iOS/Global/Components/PophoryNavigationConfigurator.swift
  pophory-iOS/Global/Components/PophoryWebViewController.swift
  pophory-iOS/Global/Extensions/UIViewController+Extension.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/AlbumDetail/View/AlbumDetailView.swift
  pophory-iOS/Screen/Auth/ViewControllers/IDInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/NameInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/PickAlbumCoverViewController.swift
  pophory-iOS/Screen/Mypage/View/MyPageRootView.swift
  pophory-iOS/Screen/Onboarding/ViewContoller/OnboardingViewController.swift
  pophory-iOS/Screen/Settings/ViewController/SettingsViewController.swift
Labels: 다은🔥, Fix 🔧

#132 [Fix] 자잘한 버그 수정
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Global/Components/PophoryButtonBuilder.swift
  pophory-iOS/Global/Components/PophoryNavigationConfigurator.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/AlbumDetail/View/AlbumDetailView.swift
  pophory-iOS/Screen/Auth/Views/IDInputView.swift
  pophory-iOS/Screen/Auth/Views/NameInputView.swift
  pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
Labels: Bug 👿, 준☀️, 다은🔥, Fix 🔧

#140 [Fix] #139 PhotoAPI 수정 및 AddPhoto AlbumID 수정
  pophory-iOS/Network/API/PhotoAPI.swift
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
Labels: 다예✨, Fix 🔧

#141 [Feat] #115 사진 삭제 API 연결
  pophory-iOS/Global/Components/Base/BaseViewController.swift
  pophory-iOS/Global/Components/PophoryNavigationConfigurator.swift
  pophory-iOS/Network/API/PhotoAPI.swift
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/PhotoDetail/ViewController/PhotoDetailViewController.swift
Labels: 다예✨, Feat 🛠️

#143 [Fix] #142 선택 사진 권한 허용 오류 해결
  pophory-iOS/Global/Components/LimitedImagePicker/PHPickerLimitedPhotoViewController.swift
Labels: 다예✨, Fix 🔧

#145 [Add] #144 사진 다 찼을 시 팝업 구현
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
Labels: 다예✨, Add ➕

#151 [Fix] - 기기대응
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Global/Extensions/CGSize+Extension.swift
  pophory-iOS/Global/Extensions/ConstraintMaker+Extension.swift
  pophory-iOS/Global/Extensions/UIView+Extension.swift
  pophory-iOS/Global/Resources/SceneDelegate.swift
  pophory-iOS/Global/Utilities/KeyboardManager.swift
  pophory-iOS/Network/Common/BaseURLConstant.swift
  pophory-iOS/Screen/Auth/ViewControllers/IDInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/NameInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/PickAlbumCoverViewController.swift
  pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
  pophory-iOS/Screen/Auth/Views/StartPophoryView.swift
  pophory-iOS/Screen/HomeAlbum/HomeAlbumView.swift
  pophory-iOS/Screen/Onboarding/View/Cell/OnboardingContentCollectionViewCell.swift
  pophory-iOS/Screen/Onboarding/View/OnboardingView.swift
  pophory-iOS/Screen/Onboarding/ViewContoller/OnboardingViewController.swift
Labels: Fix 🔧

#153 [Chore] #135 - 정규식 작성정책, UX라이팅 변경
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Global/Resources/SceneDelegate.swift
  pophory-iOS/Screen/Auth/Views/IDInputView.swift
  pophory-iOS/Screen/Auth/Views/NameInputView.swift
  pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
  pophory-iOS/Screen/Onboarding/View/OnboardingView.swift
Labels: 준☀️, Chore 🧹

#150 [Feat] #149 Presigned URL 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Network/API/PhotoAPI.swift
  pophory-iOS/Network/Common/URLConstants.swift
  pophory-iOS/Network/Models/Photo/PatchPresignedURLRequestDTO.swift
  pophory-iOS/Network/Models/Photo/PostPhotoRequestDTO.swift
  pophory-iOS/Network/Repository/DefaultPhotoRepository.swift
  pophory-iOS/Network/Repository/Protocol/PhotoRepository.swift
  pophory-iOS/Screen/AddPhoto/Network/AddPhotoNetworkManager.swift
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
Labels: 다예✨, Feat 🛠️

#162 [Feat] #157 - 에러 예외처리 뷰 UI구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Global/Components/PophoryButtonBuilder.swift
  pophory-iOS/Global/Components/PophoryErrorViewController.swift
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/OnboardingImage4.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/OnboardingImage4.imageset/img_onboarding04.png
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/OnboardingImage4.imageset/img_onboarding04@2x.png
  pophory-iOS/Global/Resources/Assets.xcassets/OnboardingImg/OnboardingImage4.imageset/img_onboarding04@3x.png
  pophory-iOS/Global/Resources/Assets.xcassets/img_networkError.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/img_networkError.imageset/img_networkError.svg
  pophory-iOS/Screen/Auth/ViewControllers/IDInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/NameInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/PickAlbumCoverViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/StartPophoryViewController.swift
  pophory-iOS/Screen/Onboarding/View/OnboardingView.swift
  pophory-iOS/Screen/Onboarding/ViewContoller/OnboardingViewController.swift
Labels: 준☀️, Feat 🛠️

#163 [Feat] 마이페이지 V2 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/PophoryWebViewController.swift
  pophory-iOS/Global/Consts/ColorLiterals.swift
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Resources/Assets.xcassets/ckeckBigIconWhite.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/ckeckBigIconWhite.imageset/ckeckBigIconWhite.svg
  pophory-iOS/Global/Resources/Assets.xcassets/myPageShareBanner.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/myPageShareBanner.imageset/마이페이지_일러스트.png
  pophory-iOS/Global/Resources/Assets.xcassets/myPageShareBanner.imageset/마이페이지_일러스트@2x.png
  pophory-iOS/Global/Resources/Assets.xcassets/myPageShareBanner.imageset/마이페이지_일러스트@3x.png
  pophory-iOS/Network/API/MemberAPI.swift
  pophory-iOS/Network/API/PhotoAPI.swift
  pophory-iOS/Network/Models/Member/FetchMyPageResponseDTO.swift
  pophory-iOS/Network/Models/Member/FetchUserInfoResponseDTO.swift
  pophory-iOS/Network/Models/Photo/PhotoUrlResponseDto.swift
  pophory-iOS/Network/Models/Photos.swift
  pophory-iOS/Network/Repository/DefaultMemberRepository.swift
  pophory-iOS/Network/Repository/DefaultPhotoRepository.swift
  pophory-iOS/Network/Repository/Protocol/MemberRepository.swift
  pophory-iOS/Network/Repository/Protocol/PhotoRepository.swift
  pophory-iOS/Screen/AlbumDetail/View/PhotoCollectionViewCell.swift
  pophory-iOS/Screen/Mypage/Network/MyPageNetworkManager.swift
  pophory-iOS/Screen/Mypage/View/MyPage/MyPageBannerView.swift
  pophory-iOS/Screen/Mypage/View/MyPage/MyPageRootView.swift
  pophory-iOS/Screen/Mypage/View/SharePhoto/SharePhotoRootView.swift
  pophory-iOS/Screen/Mypage/ViewController/MypageViewController.swift
  pophory-iOS/Screen/Mypage/ViewController/SharePhotoViewController.swift
Labels: 다은🔥, Feat 🛠️

#165 [Add] #164 사진 공유 API 세팅
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Network/API/ShareAPI.swift
  pophory-iOS/Network/Common/NetworkService.swift
  pophory-iOS/Network/Models/Share/PatchSharePhotoRequestDTO.swift
  pophory-iOS/Network/Models/Share/PostSharePhotoRequestDTO.swift
  pophory-iOS/Network/Repository/DefaultShareRepository.swift
  pophory-iOS/Network/Repository/Protocol/ShareRepository.swift
Labels: 다예✨, Add ➕

#171 [Feat] #169 - 내 사진 뷰 공유버튼 UI 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Navigation/PophoryNavigationConfigurator.swift
  pophory-iOS/Global/Components/Navigation/PophoryNavigationController.swift
  pophory-iOS/Global/Components/PophoryNavigationConfigurator.swift
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Extensions/UIViewController+Extension.swift
  pophory-iOS/Global/Resources/Assets.xcassets/Share.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/Share.imageset/Share.svg
  pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
  pophory-iOS/Screen/EditAlbumCover/ViewController/EditAlbumViewController.swift
  pophory-iOS/Screen/PhotoDetail/ViewController/PhotoDetailViewController.swift
Labels: 준☀️, Feat 🛠️

#177 [Add] #173 - 상단 인디케이터 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Global/Extensions/UIViewController+Extension.swift
  pophory-iOS/Global/Utilities/KeyboardManager.swift
  pophory-iOS/Screen/Auth/ViewControllers/IDInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/NameInputViewController.swift
  pophory-iOS/Screen/Auth/ViewControllers/PickAlbumCoverViewController.swift
  pophory-iOS/Screen/Auth/Views/IDInputView.swift
  pophory-iOS/Screen/Auth/Views/NameInputView.swift
  pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
Labels: 준☀️, Chore 🧹, Add ➕

#180 [Fix] #170 겹치는 에셋명 변경
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Screen/Share/ShareView.swift
Labels: 다예✨, Fix 🔧
