Repository TeamPophory/pophory-iOS, pull requests merged in 2023-10, with the labels that each got.

#231 [Chore] #230 - .gitignore에 xcshareddata 추가
  .gitignore
Labels: Chore 🧹, 윤서💡

#226 [Fix] #225 - 앨범 이미지 탈락 이슈
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_1.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_1.imageset/앨범커버_가족1_최종_1.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_1.imageset/앨범커버_가족1_최종_1.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_1.imageset/앨범커버_가족1_최종_1@2x.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_1.imageset/앨범커버_가족1_최종_1@2x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_1.imageset/앨범커버_가족1_최종_1@3x.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_1.imageset/앨범커버_가족1_최종_1@3x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_2.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_2.imageset/앨범커버_가족2_최종_1.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_2.imageset/앨범커버_가족2_최종_1.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_2.imageset/앨범커버_가족2_최종_1@2x.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_2.imageset/앨범커버_가족2_최종_1@2x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_2.imageset/앨범커버_가족2_최종_1@3x.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_family_2.imageset/앨범커버_가족2_최종_1@3x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_1.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_1.imageset/앨범커버_사랑1_최종_1.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_1.imageset/앨범커버_사랑1_최종_1@2x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_1.imageset/앨범커버_사랑1_최종_1@3x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_1.imageset/앨범커버_사랑2_최종_1.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_1.imageset/앨범커버_사랑2_최종_1@2x.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_1.imageset/앨범커버_사랑2_최종_1@3x.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_2.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_2.imageset/앨범커버_사랑1_최종_1.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_2.imageset/앨범커버_사랑1_최종_1@2x.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_2.imageset/앨범커버_사랑1_최종_1@3x.png
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_2.imageset/앨범커버_사랑2_최종_1.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_2.imageset/앨범커버_사랑2_최종_1@2x.svg
  pophory-iOS/Global/Resources/Assets.xcassets/AlbumCover/ic_album_cover_love_2.imageset/앨범커버_사랑2_최종_1@3x.svg
Labels: 준☀️, Fix 🔧

#232 [Feat] #229 - 앨범 커버 편집 시 광고 보기 기능 구현
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/PophoryButtonBuilder.swift
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Resources/AppDelegate.swift
  pophory-iOS/Global/Resources/Assets.xcassets/img_AD.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/img_AD.imageset/img_AD.svg
  pophory-iOS/Global/Resources/SceneDelegate.swift
  pophory-iOS/Global/Supporting Files/Info.plist
  pophory-iOS/Screen/EditAlbumCover/ViewController/EditAlbumViewController.swift
Labels: Feat 🛠️, Chore 🧹, 윤서💡

#241 [Fix] #238 - 갤러리에서 공유 시 백버튼 안먹는 이슈 해결
  pophory-iOS/Global/Resources/SceneDelegate.swift
Labels: 다예✨, Fix 🔧

#242 [Feat] #239 - 광고 배너 클릭 시 웹뷰로 이동하기
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Consts/WebViewURLList.swift
  pophory-iOS/Global/Resources/Assets.xcassets/MyPage/banner_ad.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/MyPage/banner_ad.imageset/banner_ad.svg
  pophory-iOS/Global/Supporting Files/Info.plist
  pophory-iOS/Screen/Mypage/View/MyPage/MyPageRootView.swift
  pophory-iOS/Screen/Mypage/ViewController/MypageViewController.swift
  pophory-iOS/Screen/Settings/ViewController/SettingsViewController.swift
Labels: Feat 🛠️, 윤서💡

#245 [Feat] #228 - Qr 코드 인식
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Global/Components/Base/BaseInputView.swift
  pophory-iOS/Global/Components/Base/BaseViewController.swift
  pophory-iOS/Global/Components/Navigation/PophoryNavigationConfigurator.swift
  pophory-iOS/Global/Components/Navigation/PophoryNavigationController.swift
  pophory-iOS/Global/Consts/ImageLiterals.swift
  pophory-iOS/Global/Extensions/UIViewController+Extension.swift
  pophory-iOS/Global/Protocols/KeyboardFollowable.swift
  pophory-iOS/Global/Protocols/NextButtonDelegate.swift
  pophory-iOS/Global/Protocols/TokenExpirationHandling.swift
  pophory-iOS/Global/Resources/Assets.xcassets/IC/qrUploadButton.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/IC/qrUploadButton.imageset/qrUploadButton.png
  pophory-iOS/Global/Resources/Assets.xcassets/IC/qrUploadButton.imageset/qrUploadButton@2x.png
  pophory-iOS/Global/Resources/Assets.xcassets/IC/qrUploadButton.imageset/qrUploadButton@3x.png
  pophory-iOS/Global/Resources/Assets.xcassets/IC/uploadFromAlbumButton.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/IC/uploadFromAlbumButton.imageset/uploadFromAlbumButton.png
  pophory-iOS/Global/Resources/Assets.xcassets/IC/uploadFromAlbumButton.imageset/uploadFromAlbumButton@2x.png
  pophory-iOS/Global/Resources/Assets.xcassets/IC/uploadFromAlbumButton.imageset/uploadFromAlbumButton@3x.png
  pophory-iOS/Global/Resources/Assets.xcassets/QRScanner/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/QRScanner/qrScannerFrame.imageset/Contents.json
  pophory-iOS/Global/Resources/Assets.xcassets/QRScanner/qrScannerFrame.imageset/Group 427320551.png
  pophory-iOS/Global/Resources/Assets.xcassets/QRScanner/qrScannerFrame.imageset/Group 427320551@2x.png
  pophory-iOS/Global/Resources/Assets.xcassets/QRScanner/qrScannerFrame.imageset/Group 427320551@3x.png
  pophory-iOS/Global/Supporting Files/Info.plist
  pophory-iOS/Network/Common/NetworkResult.swift
  pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
  pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
  pophory-iOS/Screen/HomeAlbum/HomeAlbumViewController.swift
  pophory-iOS/Screen/Mypage/ViewController/MypageViewController.swift
  pophory-iOS/Screen/PhotoUpload/PhotoUploadModalViewController.swift
  pophory-iOS/Screen/QRDownload/QRDownLoadWebViewController.swift
  pophory-iOS/Screen/QRScanner/QRScannerView.swift
  pophory-iOS/Screen/QRScanner/QRScannerViewController.swift
  pophory-iOS/Screen/TabBar/TabBarViewController.swift
Labels: 준☀️, Feat 🛠️

#246 [Feat] #240 - 광고 API 연결
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS.xcodeproj/xcshareddata/xcschemes/pophory-Release.xcscheme
  pophory-iOS/Global/Resources/AppDelegate.swift
  pophory-iOS/Global/Supporting Files/Info.plist
  pophory-iOS/Network/API/AdAPI.swift
  pophory-iOS/Network/Common/NetworkService.swift
  pophory-iOS/Network/Common/PophoryAdManager.swift
  pophory-iOS/Network/Common/URLConstants.swift
  pophory-iOS/Network/Models/Ad/FetchAdResponseDTO.swift
  pophory-iOS/Network/Repository/BaseRepository.swift
  pophory-iOS/Network/Repository/DefaultAdRepository.swift
  pophory-iOS/Network/Repository/Protocol/AdRepository.swift
  pophory-iOS/Screen/EditAlbumCover/ViewController/EditAlbumViewController.swift
  pophory-iOS/Screen/TabBar/TabBarViewController.swift
Labels: Feat 🛠️, 윤서💡

#248 [Feat] #247 - 프로젝트 파일 수정 및 광고 로직 수정
  pophory-iOS.xcodeproj/project.pbxproj
  pophory-iOS/Screen/EditAlbumCover/ViewController/EditAlbumViewController.swift
Labels: Fix 🔧, 윤서💡
